export const CREATE_PROTOCOLE = "CREATE_PROTOCOLE";
export const RETRIEVE_PROTOCOLES = "RETRIEVE_PROTOCOLES";
export const UPDATE_PROTOCOLE = "UPDATE_PROTOCOLE";
export const DELETE_PROTOCOLE = "DELETE_PROTOCOLE";
