export const CREATE_MODEL = "CREATE_MODEL";
export const RETRIEVE_MODELS = "RETRIEVE_MODELS";
export const UPDATE_MODEL = "UPDATE_MODEL";
export const DELETE_MODEL = "DELETE_MODEL";
export const FILTER_MODELS = "FILTER_MODELS";